2024-03-12 10:14:50.298241+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "create table [*]user (id bigint generated by default as identity, username varchar(255), primary key (id))"; expected "identifier"; SQL statement:
create table user (id bigint generated by default as identity, username varchar(255), primary key (id)) [42001-224]
2024-03-12 10:14:50.306206+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "alter table if exists user_viewing_history add constraint FK58aoxgruvej418wk3wobpr0q1 foreign key (user_id) references [*]user"; expected "identifier"; SQL statement:
alter table if exists user_viewing_history add constraint FK58aoxgruvej418wk3wobpr0q1 foreign key (user_id) references user [42001-224]
2024-03-12 12:47:51.228103+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "create table [*]user (id bigint generated by default as identity, username varchar(255), primary key (id))"; expected "identifier"; SQL statement:
create table user (id bigint generated by default as identity, username varchar(255), primary key (id)) [42001-224]
2024-03-12 12:47:51.236929+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "alter table if exists user_viewing_history add constraint FK58aoxgruvej418wk3wobpr0q1 foreign key (user_id) references [*]user"; expected "identifier"; SQL statement:
alter table if exists user_viewing_history add constraint FK58aoxgruvej418wk3wobpr0q1 foreign key (user_id) references user [42001-224]
2024-03-12 13:03:50.415094+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "create table [*]user (id bigint generated by default as identity, username varchar(255), primary key (id))"; expected "identifier"; SQL statement:
create table user (id bigint generated by default as identity, username varchar(255), primary key (id)) [42001-224]
2024-03-12 13:03:50.421805+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "alter table if exists user_viewing_history add constraint FK58aoxgruvej418wk3wobpr0q1 foreign key (user_id) references [*]user"; expected "identifier"; SQL statement:
alter table if exists user_viewing_history add constraint FK58aoxgruvej418wk3wobpr0q1 foreign key (user_id) references user [42001-224]
2024-03-12 17:32:31.301515+02:00 jdbc[13]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "SHOW [*]* FROM MOVIES"; SQL statement:
SHOW * FROM MOVIES [42000-224]
2024-03-12 17:51:05.838428+02:00 jdbc[13]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "USERSUSERS_VIEWING_HISTORY" not found; SQL statement:
SELECT * FROM USERSUSERS_VIEWING_HISTORY [42102-224]
2024-03-20 09:38:27.612956+02:00 jdbc[15]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-224]
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:218)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:135)
	at org.h2.Driver.connect(Driver.java:59)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:733)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:690)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 16 more
